name: pxblocs
description: Reusable Blocs
# version: 1.0.0
# homepage: https://www.example.com
# author: PeterX <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
  bloc: ^0.12.0
  pxrepos:
    path: ../pxrepos
    
dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
  
#flutter:
 #  uses-material-design: true