name: pxrepos
description: A sample command-line application.
# version: 1.0.0
# homepage: https://www.example.com
# author: PeterX <email@example.com>

environment:
  sdk: '>=2.1.0 <3.0.0'

dependencies:
 #firebase_auth: 0.5.19
 #cloud_firestore: 0.7.4 
 #intl: ^0.15.4
 equatable: ^0.2.3
 #path_provider: ^0.4.1
   
#  path: ^1.4.1

dev_dependencies:
  pedantic: ^1.0.0
  test: ^1.0.0
